FROM astronomerinc/ap-airflow:0.7.5-1.10.1-onbuild


# https://github.com/astronomerio-archive/docker-airflow/blob/master/Dockerfile


############# install posgre   ################
#RUN bash setup_posgre_local.sh


# Jupyter ports
EXPOSE 8888 
