FROM astronomerinc/ap-airflow:latest-onbuild

# https://github.com/astronomerio-archive/docker-airflow/blob/master/Dockerfile


############# install posgre   ################
ENTRYPOINT ["/bin/bash", "/setup_posgre_local.sh"]
